# see https://github.com/DavidAnson/markdownlint/blob/v0.32.1/schema/.markdownlint.yaml
# and https://github.com/DavidAnson/markdownlint-cli2?tab=readme-ov-file#markdownlintyaml-or-markdownlintyml

# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

# disable line length checking
MD013: false

# MD033/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md033.md
MD033:
  # Allowed elements
  allowed_elements: ["details", "summary"]
