[user]
name = "Felix Rath"
email = "felixm.rath@gmail.com"

[ui]
paginate = "auto"
default-command = "log"
pager = "less -FRX"
# diff.format = "git"
diff.tool = ["difft", "--color=always", "$left", "$right"]
