font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

symbol_map U+E000-U+F8FF Symbols Nerd Font Mono
symbol_map U+E000-U+E00A,U+EA60-U+EBEB,U+E0A0-U+E0C8,U+E0CA,U+E0CC-U+E0D7,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B7,U+E700-U+E8EF,U+ED00-U+EFC1,U+F000-U+F2FF,U+F300-U+F381,U+F400-U+F533,U+F0001-U+F1AF0 Symbols Nerd Font Mono

term xterm-kitty
terminfo_type path
shell_integration enabled
notify_on_cmd_finish unfocused 10.0 notify focus next

map kitty_mod+t new_tab_with_cwd

linux_display_server auto
wayland_enable_ime yes

copy_on_select clipboard
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
strip_trailing_spaces smart

allow_hyperlinks yes
underline_hyperlinks hover
enable_audio_bell no

tab_bar_style fade
tab_powerline_style round
tab_bar_min_tabs 2
tab_bar_margin_width 5.0
tab_bar_margin_height 5.0 10.0
tab_bar_align center
tab_separator " |"
tab_activity_symbol none

auto_reload_config 0.5

allow_remote_control yes

include theme.conf
