# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # need to escape spaces in strings: https://github.com/NixOS/nixpkgs/issues/254331
  boot.kernelParams = [
    # 2025-09-13: Trying to fix the errors below, got the param from here: https://bbs.archlinux.org/viewtopic.php?id=302499 - seems to work so far
    #
    # ```console
    # $ journalctl -b -2
    # Sep 11 19:10:20 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # Sep 11 19:10:20 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # Sep 11 19:10:20 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # Sep 11 19:10:20 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # Sep 11 19:10:21 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # Sep 11 19:10:21 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # Sep 11 19:10:21 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # Sep 11 19:10:21 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # Sep 11 19:10:21 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # Sep 11 19:10:22 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # Sep 11 19:10:22 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # Sep 11 19:10:22 nixos-work kernel: amdgpu 0000:03:00.0: [drm] *ERROR* dc_dmub_srv_log_diagnostic_data: DMCUB error - collecting diagnostic data
    # ```
    "amdgpu.dcdebugmask=0x10"

    # 2025-10-26: None of this helped, sadly :(

    # Let's not announce ourselves as Linux, so maybe we get to have Wifi 🙃
    # https://bbs.archlinux.org/viewtopic.php?pid=1190086
    # "acpi_osi=\"!Linux\""
    # "acpi_osi="
    # "acpi_osi=\"Windows 2021\""

    # "acpi_osi=!"
    # "acpi_osi=\"Windows 2021\""
  ];

  fileSystems."/" = {
    device = "rpool/root/nixos";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "rpool/home";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E335-1CB9";
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/967d766e-4e86-41c9-97db-40f466f538e0"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0f4u1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    enableAllFirmware = true;
    cpu.amd.updateMicrocode = true;
    enableRedistributableFirmware = true;
    # enableAllHardware = true;

    bluetooth = {
      enable = true;
      powerOnBoot = true;

      # from https://discourse.nixos.org/t/bluetooth-not-working/27812
      settings = {
        General = {
          # Name = "Hello";
          # FastConnectable = "true";
          ControllerMode = "dual";
          Experimental = "true";
        };
        Policy = {
          AutoEnable = "true";
        };
      };
    };

    # according to this wiki, because my GPU is a bit old apparently: https://wiki.nixos.org/wiki/AMD_GPU#AMDVLK
    # graphics = {
    #   extraPackages = with pkgs; [
    #     amdvlk
    #   ];
    #   # graphics.extraPackages32 = with pkgs; [
    #   #   driversi686Linux.amdvlk
    #   # ];
    # };

    amdgpu.legacySupport.enable = true;
  };

  # from https://nixos.wiki/wiki/Laptop and https://github.com/AdnanHodzic/auto-cpufreq/blob/v1.9.9/auto-cpufreq.conf-example
  # this helped a lot/just magically fixed my perf/temp problems!
  services.auto-cpufreq = {
    enable = true;
    settings = {
      battery = {
        governor = "powersave";
        turbo = "auto";
      };
      charger = {
        governor = "performance";
        turbo = "auto";
      };
    };
  };

  # have to disable this, as the two conflict.
  services.power-profiles-daemon.enable = false;
}
