# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # generated through `nixos-generate-config` from virtualbox-boot and native boot
  boot.initrd.availableKernelModules = [
    "ata_piix"
    "ohci_pci"
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]
    ++ # from `sudo sensors-detect`
    [ "coretemp" "nct6775" ];

  # for fixing some NVIDIA/NVK-stuff, maybe (see https://discourse.nixos.org/t/drm-kernel-driver-nvidia-drm-in-use-nvk-requires-nouveau/42222/18)
  # actually I think this caused a kernel bug in the nvidia-driver that crashed my pc when waking up from suspend
  # boot.kernelParams = [ "nvidia-drm.fbdev=1" ];
  # hardware.nvidia.modesetting.enable = true;
  # alternative (also from that thread/linked somewhere):
  # this one works :)
  environment.sessionVariables.VK_DRIVER_FILES = "/run/opengl-driver/share/vulkan/icd.d/nvidia_icd.x86_64.json";

  # see https://nixos.wiki/wiki/Nvidia#Modifying_NixOS_Configuration
  # and https://discourse.nixos.org/t/all-nividia-drivers-crash-or-do-not-work/47427/7?u=futile
  hardware.nvidia = {
    # seems this like should almost always be enabled.
    modesetting.enable = true;

    # trying to fix crashes when resuming from suspend
    # false crashing (color garble on screen after wake up) - 2024-09-24
    # true crashing (black screen after wake up) - 2024-10-10
    # false crashing (screen doesn't turn back on after wake up) - 2024-10-10
    powerManagement.enable = true;
    powerManagement.finegrained = false;

    # just enable the `nvidia-settings` tool; should be default, but why not explicitly.
    nvidiaSettings = true;

    # not supported for my GPU :( https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus
    # (i.e., system won't boot/switch into graphical mode when booting)
    open = false;

    # this one (535) fixes my crash after resume-from-suspend! :tada:
    # See:
    # https://github.com/NixOS/nixpkgs/blob/feb2849fdeb70028c70d73b848214b00d324a497/pkgs/os-specific/linux/nvidia-x11/default.nix#L108-L119
    # https://bbs.archlinux.org/viewtopic.php?pid=2155426#p2155426
    # https://discourse.nixos.org/t/random-freeze-of-system/44766
    # - Sadly did not fix it, I think :( let's observe for now - 2024-07-14
    # Let's try stable/whatever the default is again..
    # package = config.boot.kernelPackages.nvidiaPackages.legacy_535;
  };

  # nvidia let's go
  services.xserver.videoDrivers = [
    "nvidia"
    #"nouveau" 
  ];


  # care; this might need something like:
  # `with config.boot.kernelPackages;`
  # see https://nixos.wiki/wiki/Linux_kernel#Custom_kernel_modules
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "rpool/root/nixos";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "rpool/home";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C0AE-C552";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/3d2fa5e1-f9f8-468e-a5e1-0bd0942a3c04"; }];

  # Does (currently) not work with _latest-kernel
  # virtualisation.virtualbox.guest.enable = true;

  # not required to circumvent the timeout at boot, but when running `nixos-rebuild switch`
  systemd.units."dev-vboxguest.device".text = ''
    [Unit]
    ConditionVirtualization=oracle
  '';

  hardware.cpu.intel.updateMicrocode = true;

  # for rtl8192ee (wifi) firmware
  hardware.enableRedistributableFirmware = true;
}
