#:schema https://developers.openai.com/codex/config-schema.json

model = "gpt-5.4"
model_reasoning_effort = "medium"
model_verbosity = "medium"
personality = "pragmatic"

[tools]
view_image = true

[tui]
status_line = [
  "model-with-reasoning",
  "context-remaining",
  "current-dir",
  "git-branch",
  "five-hour-limit",
]
terminal_title = ["spinner", "project", "app-name"]

# DeepWiki mcp: https://docs.devin.ai/work-with-devin/deepwiki-mcp
[mcp_servers.DeepWiki]
url = "https://mcp.deepwiki.com/mcp"
